name: project
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  permission_handler: ^10.2.0
  http: ^1.2.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  lottie: ^3.1.0
  animated_text_kit: ^4.2.1
  provider: ^6.0.1
  google_maps_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
